export { default as NavBar } from './navbar/navbar';
export { default as About } from './about/about';
export { default as Education } from './education/education';
export { default as Skills } from './skills/skills';
export { default as Experience } from './experience/experience';
export { default as Projects } from './projects/projects';
export { default as ContactMe } from './contactme/contactme';
export { default as Research } from './research/research';
export { default as SlidingToggle } from './slidingToggle/slidingToggle';